[package]
name = "glint-sys"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
glint-core.workspace = true
anyhow.workspace = true
log.workspace = true
windows = { workspace = true, features = ["ApplicationModel_DataTransfer", "Storage", "Win32_System_Time"] }
windows-core.workspace = true
serde_json = "1.0.151"
windows-collections = "0.3.2"
